{% set name = "enterprise_extensions" %}
{% set version = "2.0" %}

package:
    name: "{{ name|lower }}"
    version: "{{ version }}"

source:
    git_url: https://github.com/nanograv/enterprise_extensions.git
    # git_rev:
    git_depth: 1

build:
    number: 1

# test:
#     source_files:
#         - tests/
#     commands:
#         # run tests for enterprise here:
#         # or we could make a test.sh script

requirements:
    build:
        - python =3.7

    host:
        - python =3.7
        - enterprise

    run:
        - python =3.7
        - enterprise

